
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directory contents
      run: ls -al

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore Softwareprozesse/ConsoleApp1/ConsoleApp1.sln

    - name: Build
      run: dotnet build Softwareprozesse/ConsoleApp1/ConsoleApp1.sln
